# Generated by Django 4.2.3 on 2023-08-01 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BranchAddress', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchaddress',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f7a13408-ea54-436f-b294-ddc4607b9ee5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
