# Generated by Django 4.2.3 on 2023-08-01 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Country', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.UUIDField(default=uuid.UUID('bbd2bf1c-77e6-4500-8da9-7f6c612adf4f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
