# Generated by Django 4.2.3 on 2023-08-02 05:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Country', '0002_alter_country_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.UUIDField(default=uuid.UUID('aa35053c-737f-4764-8fc1-5f50acfde9ce'), editable=False, primary_key=True, serialize=False),
        ),
    ]
