# Generated by Django 4.2.3 on 2023-07-10 13:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Order', '0001_initial'),
        ('Card', '0001_initial'),
        ('Address', '0001_initial'),
        ('Role', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('9d9fd9f0-8668-4f32-b70b-676e039efb4c'), editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('surname', models.CharField(max_length=50)),
                ('phone_number', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('userAddress', models.ManyToManyField(to='Address.address')),
                ('userCard', models.ManyToManyField(to='Card.card')),
                ('userOrder', models.ManyToManyField(to='Order.order')),
                ('userRole', models.ManyToManyField(to='Role.role')),
            ],
        ),
    ]
