# Generated by Django 4.2.3 on 2023-07-09 19:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f4ac2aad-d36f-4ef3-b835-e1fd7d96e8a8'), editable=False, primary_key=True, serialize=False),
        ),
    ]
