# Generated by Django 4.2.3 on 2023-07-09 20:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9f866d46-94aa-4d5d-8c50-36ac3e4473e9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
