# Generated by Django 4.2.3 on 2023-07-09 20:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7571a31e-7638-4f40-b246-bc55b081fbf4'), editable=False, primary_key=True, serialize=False),
        ),
    ]
