# Generated by Django 4.2.3 on 2023-07-09 20:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Role', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.UUIDField(default=uuid.UUID('52d5375e-5d69-4787-9921-3b6da56ed742'), editable=False, primary_key=True, serialize=False),
        ),
    ]
