# Generated by Django 4.2.3 on 2023-07-09 20:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Role', '0002_alter_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d461a251-52c6-4ff5-8004-f4076074c636'), editable=False, primary_key=True, serialize=False),
        ),
    ]
