# Generated by Django 4.2.3 on 2023-07-09 20:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Role', '0003_alter_role_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.UUIDField(default=uuid.UUID('29886395-238a-4f52-83c2-800e9620f6dc'), editable=False, primary_key=True, serialize=False),
        ),
    ]
