# Generated by Django 4.2.3 on 2023-07-09 20:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ba9a04d2-862f-4e37-b22a-7cef9425b692'), editable=False, primary_key=True, serialize=False),
        ),
    ]
