# Generated by Django 4.2.3 on 2023-07-09 20:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('UserRole', '0002_alter_userrole_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7d3f2074-a72a-41fb-a5ef-4a09a2f9e658'), editable=False, primary_key=True, serialize=False),
        ),
    ]
