# Generated by Django 4.2.3 on 2023-07-10 13:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('HouseType', '0001_initial'),
        ('City', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('2f91b87c-4285-46ee-886a-2cf182e68d94'), editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=50)),
                ('house', models.CharField(max_length=50)),
                ('apartment', models.IntegerField()),
                ('entrance', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='City.city')),
                ('house_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HouseType.housetype')),
            ],
        ),
    ]
