# Generated by Django 4.2.3 on 2023-08-02 05:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('Address', '0002_alter_address_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='house_type',
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='Users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='apartment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='entrance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.UUIDField(default=uuid.UUID('fc20335d-a576-48ab-b0f7-92b6e782c3e9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
