# Generated by Django 4.2.3 on 2023-08-01 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('HouseType', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housetype',
            name='id',
            field=models.UUIDField(default=uuid.UUID('cf278cbf-d6e6-4ce4-b5fa-b0d5c31fba30'), editable=False, primary_key=True, serialize=False),
        ),
    ]
