# Generated by Django 4.2.3 on 2023-08-02 05:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('HouseType', '0002_alter_housetype_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housetype',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a7ae0526-13a8-4f0d-8aaf-418333ff01fd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
