# Generated by Django 4.2.3 on 2023-08-01 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Courier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a22cb03e-a458-4ec7-b5d3-b645c7822b62'), editable=False, primary_key=True, serialize=False),
        ),
    ]
