# Generated by Django 4.2.3 on 2023-08-02 05:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Courier', '0002_alter_courier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courier',
            name='id',
            field=models.UUIDField(default=uuid.UUID('545743e9-bb61-4276-8241-c25d7f418e5d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
