# Generated by Django 4.2.3 on 2023-08-01 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5de0ad6b-6e3f-42d7-b1e5-bb9910c4dd5a'), editable=False, primary_key=True, serialize=False),
        ),
    ]
