# Generated by Django 4.2.3 on 2023-08-02 05:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Branch', '0002_alter_branch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c0edbddd-c5e3-4b59-acd1-794b87180fe6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
