# Generated by Django 4.2.3 on 2023-08-01 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a12cabd7-7470-45bc-935a-7daf94615293'), editable=False, primary_key=True, serialize=False),
        ),
    ]
