# Generated by Django 4.2.3 on 2023-08-02 05:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0002_alter_food_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6636d837-4370-453d-9b61-1969f834f0e7'), editable=False, primary_key=True, serialize=False),
        ),
    ]
