# Generated by Django 4.2.3 on 2023-07-10 13:57

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Basket', '0001_initial'),
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('5899dcd9-a55c-4981-a165-4849a32b9287'), editable=False, primary_key=True, serialize=False)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Basket.basket')),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food.food')),
            ],
        ),
    ]
