# Generated by Django 4.2.3 on 2023-08-01 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Basket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9797501e-cd86-4cc4-bf99-16007bd9114f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
