# Generated by Django 4.2.3 on 2023-08-02 05:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
        ('Basket', '0002_alter_basket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='user',
            field=models.ForeignKey(default=21, on_delete=django.db.models.deletion.CASCADE, to='Users.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basket',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b804d4b0-6269-4fc6-8b89-804b35fb0176'), editable=False, primary_key=True, serialize=False),
        ),
    ]
